fuzzer_defaults: &fuzzer_defaults
  remove_arguments:
    - "-O1"
    - "-O2"
    - "-O3"
    - "-O4"
    - "-Ofast"
    - "-Os"
    - "-Oz"
    - "-Og"
  add_arguments:
    - "-g"

fuzzers:
  libfuzzer:
    <<: *fuzzer_defaults
    replace_command: "clang-6.0"
    remove_arguments+:
      - "-fomit-frame-pointer"
    add_arguments+:
    - "-fno-omit-frame-pointer"
    - "-fsanitize=fuzzer-no-link"
    - "-Og"
  afl:
    <<: *fuzzer_defaults
    replace_command: "afl-gcc"
    add_arguments+:
      - "-O1"