fuzzer_defaults: &fuzzer_defaults
  remove_arguments:
    - "-O1"
    - "-O2"
    - "-O3"
    - "-O4"
    - "-Ofast"
    - "-Os"
    - "-Oz"
    - "-Og"
  add_arguments:
    - "-g"

fuzzers:
  libfuzzer:
    <<: *fuzzer_defaults
    replace_cc: "clang"
    replace_cxx: "clang++"
    remove_arguments+:
      - "-fomit-frame-pointer"
    add_arguments+:
    - "-fno-omit-frame-pointer"
    - "-fsanitize=fuzzer-no-link"
    - "-Og"
  afl:
    <<: *fuzzer_defaults
    replace_cc: "afl-clang"
    replace_cxx: "afl-clang++"
    add_arguments+:
      - "-O0"
  llvm-cov:
    <<: *fuzzer_defaults
    replace_cc: "clang"
    replace_cxx: "clang++"
    remove_arguments+:
      - "-fomit-frame-pointer"
    add_arguments+:
    - "-O0"
    - "-fno-omit-frame-pointer"
    - "-fprofile-instr-generate"
    - "-fcoverage-mapping"
