fuzzer_defaults: &fuzzer_defaults
  remove_arguments:
    - "-O1"
    - "-O2"
    - "-O3"
    - "-O4"
    - "-Ofast"
    - "-Os"
    - "-Oz"
    - "-Og"
  add_arguments:
    - "-g"
    # CFLAGS from oss-fuzz/infra/base-images/base-clang/Dockerfile
    - "-gline-tables-only"
    - "-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION"

fuzzers:
  libfuzzer:
    <<: *fuzzer_defaults
    replace_cc: "clang"
    replace_cxx: "clang++"
    remove_arguments+:
      - "-fomit-frame-pointer"
    add_arguments+:
      - "-fno-omit-frame-pointer"
      - "-fsanitize=fuzzer-no-link"
      - "-Og"
  afl:
    <<: *fuzzer_defaults
    replace_cc: "afl-clang"
    replace_cxx: "afl-clang++"
    add_arguments+:
      - "-O0"
  llvm-cov:
    <<: *fuzzer_defaults
    replace_cc: "clang"
    replace_cxx: "clang++"
    remove_arguments+:
      - "-fomit-frame-pointer"
    add_arguments+:
      - "-O0"
      - "-fno-omit-frame-pointer"
      - "-fprofile-instr-generate"
      - "-fcoverage-mapping"
